# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderUpdateEvent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orderUpdateEvent.proto',
  package='OrderUpdateEvent',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16orderUpdateEvent.proto\x12\x10OrderUpdateEvent\"\xd6\x05\n\rOrderItemInfo\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\r\n\x05wmsId\x18\x02 \x01(\t\x12\x13\n\x0b\x63reatedById\x18\x03 \x01(\x05\x12\x11\n\tcreatedOn\x18\x04 \x01(\x03\x12\x15\n\rcreatedByName\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x11\n\twmsStatus\x18\x07 \x01(\t\x12\x11\n\tcrmStatus\x18\x08 \x01(\t\x12\x10\n\x08\x66\x61rmerId\x18\t \x01(\t\x12\x10\n\x08itemName\x18\n \x01(\t\x12\x0f\n\x07skuCode\x18\x0b \x01(\t\x12\x10\n\x08quantity\x18\x0c \x01(\x05\x12\x13\n\x0borderItemId\x18\x11 \x01(\t\x12\x19\n\x11levelOneCateogroy\x18\x15 \x01(\t\x12\x18\n\x10levelTwoCategory\x18\x16 \x01(\t\x12\x1a\n\x12levelThreeCategory\x18\x17 \x01(\t\x12\x17\n\x0forderGrandTotal\x18\x18 \x01(\x02\x12\x1b\n\x13orderItemTotalPrice\x18\x19 \x01(\x02\x12\x15\n\risEditedOrder\x18\x1a \x01(\x08\x12\x17\n\x0fpreviousOrderId\x18\x1b \x01(\t\x12\x18\n\x10orderConfirmedOn\x18\x1c \x01(\x03\x12\x15\n\rorderItemUUID\x18\x1d \x01(\t\x12\x12\n\nfarmerName\x18\x1e \x01(\t\x12\x0f\n\x07mobile1\x18\x1f \x01(\t\x12\x0f\n\x07mobile2\x18  \x01(\t\x12\x0f\n\x07mobile3\x18! \x01(\t\x12\x1a\n\x12orderConfirmedById\x18\" \x01(\t\x12\x1c\n\x14orderConfirmedByName\x18# \x01(\t\x12\x16\n\x0eorderUpdatedOn\x18$ \x01(\t\x12\x18\n\x10orderUpdatedById\x18% \x01(\t\x12\x1a\n\x12orderUpdatedByName\x18& \x01(\t\x12\x1d\n\x15orderItemSellingPrice\x18\' \x01(\x02\"\'\n\x0f\x41\x63knowledgement\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32j\n\x13\x43ustomerOrderUpdate\x12S\n\x0bOrderUpdate\x12\x1f.OrderUpdateEvent.OrderItemInfo\x1a!.OrderUpdateEvent.Acknowledgement\"\x00\x62\x06proto3')
)




_ORDERITEMINFO = _descriptor.Descriptor(
  name='OrderItemInfo',
  full_name='OrderUpdateEvent.OrderItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='OrderUpdateEvent.OrderItemInfo.orderId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wmsId', full_name='OrderUpdateEvent.OrderItemInfo.wmsId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdById', full_name='OrderUpdateEvent.OrderItemInfo.createdById', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdOn', full_name='OrderUpdateEvent.OrderItemInfo.createdOn', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createdByName', full_name='OrderUpdateEvent.OrderItemInfo.createdByName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='OrderUpdateEvent.OrderItemInfo.source', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wmsStatus', full_name='OrderUpdateEvent.OrderItemInfo.wmsStatus', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crmStatus', full_name='OrderUpdateEvent.OrderItemInfo.crmStatus', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='farmerId', full_name='OrderUpdateEvent.OrderItemInfo.farmerId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemName', full_name='OrderUpdateEvent.OrderItemInfo.itemName', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skuCode', full_name='OrderUpdateEvent.OrderItemInfo.skuCode', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='OrderUpdateEvent.OrderItemInfo.quantity', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderItemId', full_name='OrderUpdateEvent.OrderItemInfo.orderItemId', index=12,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levelOneCateogroy', full_name='OrderUpdateEvent.OrderItemInfo.levelOneCateogroy', index=13,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levelTwoCategory', full_name='OrderUpdateEvent.OrderItemInfo.levelTwoCategory', index=14,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levelThreeCategory', full_name='OrderUpdateEvent.OrderItemInfo.levelThreeCategory', index=15,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderGrandTotal', full_name='OrderUpdateEvent.OrderItemInfo.orderGrandTotal', index=16,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderItemTotalPrice', full_name='OrderUpdateEvent.OrderItemInfo.orderItemTotalPrice', index=17,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isEditedOrder', full_name='OrderUpdateEvent.OrderItemInfo.isEditedOrder', index=18,
      number=26, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='previousOrderId', full_name='OrderUpdateEvent.OrderItemInfo.previousOrderId', index=19,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderConfirmedOn', full_name='OrderUpdateEvent.OrderItemInfo.orderConfirmedOn', index=20,
      number=28, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderItemUUID', full_name='OrderUpdateEvent.OrderItemInfo.orderItemUUID', index=21,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='farmerName', full_name='OrderUpdateEvent.OrderItemInfo.farmerName', index=22,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile1', full_name='OrderUpdateEvent.OrderItemInfo.mobile1', index=23,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile2', full_name='OrderUpdateEvent.OrderItemInfo.mobile2', index=24,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile3', full_name='OrderUpdateEvent.OrderItemInfo.mobile3', index=25,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderConfirmedById', full_name='OrderUpdateEvent.OrderItemInfo.orderConfirmedById', index=26,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderConfirmedByName', full_name='OrderUpdateEvent.OrderItemInfo.orderConfirmedByName', index=27,
      number=35, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderUpdatedOn', full_name='OrderUpdateEvent.OrderItemInfo.orderUpdatedOn', index=28,
      number=36, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderUpdatedById', full_name='OrderUpdateEvent.OrderItemInfo.orderUpdatedById', index=29,
      number=37, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderUpdatedByName', full_name='OrderUpdateEvent.OrderItemInfo.orderUpdatedByName', index=30,
      number=38, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderItemSellingPrice', full_name='OrderUpdateEvent.OrderItemInfo.orderItemSellingPrice', index=31,
      number=39, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=771,
)


_ACKNOWLEDGEMENT = _descriptor.Descriptor(
  name='Acknowledgement',
  full_name='OrderUpdateEvent.Acknowledgement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acknowledged', full_name='OrderUpdateEvent.Acknowledgement.acknowledged', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=812,
)

DESCRIPTOR.message_types_by_name['OrderItemInfo'] = _ORDERITEMINFO
DESCRIPTOR.message_types_by_name['Acknowledgement'] = _ACKNOWLEDGEMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderItemInfo = _reflection.GeneratedProtocolMessageType('OrderItemInfo', (_message.Message,), dict(
  DESCRIPTOR = _ORDERITEMINFO,
  __module__ = 'orderUpdateEvent_pb2'
  # @@protoc_insertion_point(class_scope:OrderUpdateEvent.OrderItemInfo)
  ))
_sym_db.RegisterMessage(OrderItemInfo)

Acknowledgement = _reflection.GeneratedProtocolMessageType('Acknowledgement', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGEMENT,
  __module__ = 'orderUpdateEvent_pb2'
  # @@protoc_insertion_point(class_scope:OrderUpdateEvent.Acknowledgement)
  ))
_sym_db.RegisterMessage(Acknowledgement)



_CUSTOMERORDERUPDATE = _descriptor.ServiceDescriptor(
  name='CustomerOrderUpdate',
  full_name='OrderUpdateEvent.CustomerOrderUpdate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=814,
  serialized_end=920,
  methods=[
  _descriptor.MethodDescriptor(
    name='OrderUpdate',
    full_name='OrderUpdateEvent.CustomerOrderUpdate.OrderUpdate',
    index=0,
    containing_service=None,
    input_type=_ORDERITEMINFO,
    output_type=_ACKNOWLEDGEMENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERORDERUPDATE)

DESCRIPTOR.services_by_name['CustomerOrderUpdate'] = _CUSTOMERORDERUPDATE

# @@protoc_insertion_point(module_scope)
