// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orderUpdateEvent.proto

package OrderUpdateEvent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderItemInfo struct {
	OrderId               string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	WmsId                 string   `protobuf:"bytes,2,opt,name=wmsId,proto3" json:"wmsId,omitempty"`
	CreatedById           int32    `protobuf:"varint,3,opt,name=createdById,proto3" json:"createdById,omitempty"`
	CreatedOn             int64    `protobuf:"varint,4,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedByName         string   `protobuf:"bytes,5,opt,name=createdByName,proto3" json:"createdByName,omitempty"`
	Source                string   `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	WmsStatus             string   `protobuf:"bytes,7,opt,name=wmsStatus,proto3" json:"wmsStatus,omitempty"`
	CrmStatus             string   `protobuf:"bytes,8,opt,name=crmStatus,proto3" json:"crmStatus,omitempty"`
	FarmerId              string   `protobuf:"bytes,9,opt,name=farmerId,proto3" json:"farmerId,omitempty"`
	ItemName              string   `protobuf:"bytes,10,opt,name=itemName,proto3" json:"itemName,omitempty"`
	SkuCode               string   `protobuf:"bytes,11,opt,name=skuCode,proto3" json:"skuCode,omitempty"`
	Quantity              int32    `protobuf:"varint,12,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderItemId           string   `protobuf:"bytes,17,opt,name=orderItemId,proto3" json:"orderItemId,omitempty"`
	LevelOneCateogroy     string   `protobuf:"bytes,21,opt,name=levelOneCateogroy,proto3" json:"levelOneCateogroy,omitempty"`
	LevelTwoCategory      string   `protobuf:"bytes,22,opt,name=levelTwoCategory,proto3" json:"levelTwoCategory,omitempty"`
	LevelThreeCategory    string   `protobuf:"bytes,23,opt,name=levelThreeCategory,proto3" json:"levelThreeCategory,omitempty"`
	OrderGrandTotal       float32  `protobuf:"fixed32,24,opt,name=orderGrandTotal,proto3" json:"orderGrandTotal,omitempty"`
	OrderItemTotalPrice   float32  `protobuf:"fixed32,25,opt,name=orderItemTotalPrice,proto3" json:"orderItemTotalPrice,omitempty"`
	IsEditedOrder         bool     `protobuf:"varint,26,opt,name=isEditedOrder,proto3" json:"isEditedOrder,omitempty"`
	PreviousOrderId       string   `protobuf:"bytes,27,opt,name=previousOrderId,proto3" json:"previousOrderId,omitempty"`
	OrderConfirmedOn      int64    `protobuf:"varint,28,opt,name=orderConfirmedOn,proto3" json:"orderConfirmedOn,omitempty"`
	OrderItemUUID         string   `protobuf:"bytes,29,opt,name=orderItemUUID,proto3" json:"orderItemUUID,omitempty"`
	FarmerName            string   `protobuf:"bytes,30,opt,name=farmerName,proto3" json:"farmerName,omitempty"`
	Mobile1               string   `protobuf:"bytes,31,opt,name=mobile1,proto3" json:"mobile1,omitempty"`
	Mobile2               string   `protobuf:"bytes,32,opt,name=mobile2,proto3" json:"mobile2,omitempty"`
	Mobile3               string   `protobuf:"bytes,33,opt,name=mobile3,proto3" json:"mobile3,omitempty"`
	OrderConfirmedById    string   `protobuf:"bytes,34,opt,name=orderConfirmedById,proto3" json:"orderConfirmedById,omitempty"`
	OrderConfirmedByName  string   `protobuf:"bytes,35,opt,name=orderConfirmedByName,proto3" json:"orderConfirmedByName,omitempty"`
	OrderUpdatedOn        string   `protobuf:"bytes,36,opt,name=orderUpdatedOn,proto3" json:"orderUpdatedOn,omitempty"`
	OrderUpdatedById      string   `protobuf:"bytes,37,opt,name=orderUpdatedById,proto3" json:"orderUpdatedById,omitempty"`
	OrderUpdatedByName    string   `protobuf:"bytes,38,opt,name=orderUpdatedByName,proto3" json:"orderUpdatedByName,omitempty"`
	OrderItemSellingPrice float32  `protobuf:"fixed32,39,opt,name=orderItemSellingPrice,proto3" json:"orderItemSellingPrice,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *OrderItemInfo) Reset()         { *m = OrderItemInfo{} }
func (m *OrderItemInfo) String() string { return proto.CompactTextString(m) }
func (*OrderItemInfo) ProtoMessage()    {}
func (*OrderItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_24dab3c9e939a323, []int{0}
}

func (m *OrderItemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItemInfo.Unmarshal(m, b)
}
func (m *OrderItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItemInfo.Marshal(b, m, deterministic)
}
func (m *OrderItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItemInfo.Merge(m, src)
}
func (m *OrderItemInfo) XXX_Size() int {
	return xxx_messageInfo_OrderItemInfo.Size(m)
}
func (m *OrderItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItemInfo proto.InternalMessageInfo

func (m *OrderItemInfo) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderItemInfo) GetWmsId() string {
	if m != nil {
		return m.WmsId
	}
	return ""
}

func (m *OrderItemInfo) GetCreatedById() int32 {
	if m != nil {
		return m.CreatedById
	}
	return 0
}

func (m *OrderItemInfo) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *OrderItemInfo) GetCreatedByName() string {
	if m != nil {
		return m.CreatedByName
	}
	return ""
}

func (m *OrderItemInfo) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *OrderItemInfo) GetWmsStatus() string {
	if m != nil {
		return m.WmsStatus
	}
	return ""
}

func (m *OrderItemInfo) GetCrmStatus() string {
	if m != nil {
		return m.CrmStatus
	}
	return ""
}

func (m *OrderItemInfo) GetFarmerId() string {
	if m != nil {
		return m.FarmerId
	}
	return ""
}

func (m *OrderItemInfo) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *OrderItemInfo) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *OrderItemInfo) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItemInfo) GetOrderItemId() string {
	if m != nil {
		return m.OrderItemId
	}
	return ""
}

func (m *OrderItemInfo) GetLevelOneCateogroy() string {
	if m != nil {
		return m.LevelOneCateogroy
	}
	return ""
}

func (m *OrderItemInfo) GetLevelTwoCategory() string {
	if m != nil {
		return m.LevelTwoCategory
	}
	return ""
}

func (m *OrderItemInfo) GetLevelThreeCategory() string {
	if m != nil {
		return m.LevelThreeCategory
	}
	return ""
}

func (m *OrderItemInfo) GetOrderGrandTotal() float32 {
	if m != nil {
		return m.OrderGrandTotal
	}
	return 0
}

func (m *OrderItemInfo) GetOrderItemTotalPrice() float32 {
	if m != nil {
		return m.OrderItemTotalPrice
	}
	return 0
}

func (m *OrderItemInfo) GetIsEditedOrder() bool {
	if m != nil {
		return m.IsEditedOrder
	}
	return false
}

func (m *OrderItemInfo) GetPreviousOrderId() string {
	if m != nil {
		return m.PreviousOrderId
	}
	return ""
}

func (m *OrderItemInfo) GetOrderConfirmedOn() int64 {
	if m != nil {
		return m.OrderConfirmedOn
	}
	return 0
}

func (m *OrderItemInfo) GetOrderItemUUID() string {
	if m != nil {
		return m.OrderItemUUID
	}
	return ""
}

func (m *OrderItemInfo) GetFarmerName() string {
	if m != nil {
		return m.FarmerName
	}
	return ""
}

func (m *OrderItemInfo) GetMobile1() string {
	if m != nil {
		return m.Mobile1
	}
	return ""
}

func (m *OrderItemInfo) GetMobile2() string {
	if m != nil {
		return m.Mobile2
	}
	return ""
}

func (m *OrderItemInfo) GetMobile3() string {
	if m != nil {
		return m.Mobile3
	}
	return ""
}

func (m *OrderItemInfo) GetOrderConfirmedById() string {
	if m != nil {
		return m.OrderConfirmedById
	}
	return ""
}

func (m *OrderItemInfo) GetOrderConfirmedByName() string {
	if m != nil {
		return m.OrderConfirmedByName
	}
	return ""
}

func (m *OrderItemInfo) GetOrderUpdatedOn() string {
	if m != nil {
		return m.OrderUpdatedOn
	}
	return ""
}

func (m *OrderItemInfo) GetOrderUpdatedById() string {
	if m != nil {
		return m.OrderUpdatedById
	}
	return ""
}

func (m *OrderItemInfo) GetOrderUpdatedByName() string {
	if m != nil {
		return m.OrderUpdatedByName
	}
	return ""
}

func (m *OrderItemInfo) GetOrderItemSellingPrice() float32 {
	if m != nil {
		return m.OrderItemSellingPrice
	}
	return 0
}

type Acknowledgement struct {
	Acknowledged         bool     `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_24dab3c9e939a323, []int{1}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

func init() {
	proto.RegisterType((*OrderItemInfo)(nil), "OrderUpdateEvent.OrderItemInfo")
	proto.RegisterType((*Acknowledgement)(nil), "OrderUpdateEvent.Acknowledgement")
}

func init() { proto.RegisterFile("orderUpdateEvent.proto", fileDescriptor_24dab3c9e939a323) }

var fileDescriptor_24dab3c9e939a323 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x6f, 0x53, 0xd3, 0x4e,
	0x10, 0xc7, 0x7f, 0x81, 0x1f, 0xd0, 0x2e, 0x20, 0x70, 0xfc, 0xf1, 0x44, 0x84, 0x50, 0x11, 0x33,
	0x8e, 0xd3, 0xd1, 0xa2, 0x2f, 0x40, 0x2b, 0xe3, 0xe4, 0x89, 0x75, 0x02, 0xbc, 0x80, 0xd0, 0x2c,
	0x35, 0x92, 0xe4, 0xea, 0xe5, 0xd2, 0x4e, 0x5f, 0x8c, 0xef, 0xd5, 0xb9, 0xbd, 0x70, 0x4d, 0xd2,
	0x3e, 0xdc, 0xcf, 0x77, 0x2f, 0xf7, 0xbd, 0xdd, 0xcd, 0xc2, 0x91, 0x90, 0x11, 0xca, 0xbb, 0x71,
	0x14, 0x2a, 0xbc, 0x9e, 0x60, 0xa6, 0xba, 0x63, 0x29, 0x94, 0x60, 0xbb, 0x83, 0x06, 0xef, 0xfc,
	0x6d, 0xc3, 0x36, 0x41, 0x5f, 0x61, 0xea, 0x67, 0x0f, 0x82, 0x71, 0xd8, 0xa0, 0xd3, 0x7e, 0xc4,
	0x1d, 0xd7, 0xf1, 0xda, 0xc1, 0x53, 0xc8, 0x0e, 0x60, 0x6d, 0x9a, 0xe6, 0x7e, 0xc4, 0x57, 0x88,
	0x9b, 0x80, 0xb9, 0xb0, 0x39, 0x94, 0x18, 0x2a, 0x8c, 0xbe, 0xce, 0xfc, 0x88, 0xaf, 0xba, 0x8e,
	0xb7, 0x16, 0x54, 0x11, 0x3b, 0x81, 0x76, 0x19, 0x0e, 0x32, 0xfe, 0xbf, 0xeb, 0x78, 0xab, 0xc1,
	0x1c, 0xb0, 0x0b, 0xd8, 0xb6, 0xc9, 0x3f, 0xc2, 0x14, 0xf9, 0x1a, 0x7d, 0xbd, 0x0e, 0xd9, 0x11,
	0xac, 0xe7, 0xa2, 0x90, 0x43, 0xe4, 0xeb, 0x24, 0x97, 0x91, 0xfe, 0xf6, 0x34, 0xcd, 0x6f, 0x54,
	0xa8, 0x8a, 0x9c, 0x6f, 0x90, 0x34, 0x07, 0xe6, 0xe6, 0xb4, 0x54, 0x5b, 0x46, 0xb5, 0x80, 0x1d,
	0x43, 0xeb, 0x21, 0x94, 0x29, 0x3d, 0xb5, 0x4d, 0xa2, 0x8d, 0xb5, 0x16, 0x2b, 0x4c, 0xc9, 0x10,
	0x18, 0xed, 0x29, 0xd6, 0x15, 0xca, 0x1f, 0x8b, 0xbe, 0x88, 0x90, 0x6f, 0x9a, 0x0a, 0x95, 0xa1,
	0x3e, 0xf5, 0xa7, 0x08, 0x33, 0x15, 0xab, 0x19, 0xdf, 0xa2, 0x42, 0xd8, 0x58, 0xd7, 0x49, 0xd8,
	0x42, 0x47, 0x7c, 0x8f, 0x4e, 0x56, 0x11, 0x7b, 0x0f, 0x7b, 0x09, 0x4e, 0x30, 0x19, 0x64, 0xd8,
	0x0f, 0x15, 0x8a, 0x91, 0x14, 0x33, 0x7e, 0x48, 0x79, 0x8b, 0x02, 0x7b, 0x07, 0xbb, 0x04, 0x6f,
	0xa7, 0x42, 0xc3, 0x91, 0x90, 0x33, 0x7e, 0x44, 0xc9, 0x0b, 0x9c, 0x75, 0x81, 0x19, 0xf6, 0x4b,
	0x22, 0xda, 0xec, 0xe7, 0x94, 0xbd, 0x44, 0x61, 0x1e, 0xec, 0x90, 0xb1, 0xef, 0x32, 0xcc, 0xa2,
	0x5b, 0xa1, 0xc2, 0x84, 0x73, 0xd7, 0xf1, 0x56, 0x82, 0x26, 0x66, 0x1f, 0x60, 0xdf, 0x3e, 0x81,
	0xc8, 0x4f, 0x19, 0x0f, 0x91, 0xbf, 0xa0, 0xec, 0x65, 0x92, 0xee, 0x77, 0x9c, 0x5f, 0x47, 0xb1,
	0xee, 0xbe, 0x96, 0xf9, 0xb1, 0xeb, 0x78, 0xad, 0xa0, 0x0e, 0xb5, 0x83, 0xb1, 0xc4, 0x49, 0x2c,
	0x8a, 0x7c, 0x50, 0x4e, 0xe3, 0x4b, 0xb2, 0xdb, 0xc4, 0xba, 0x0e, 0x74, 0x4d, 0x5f, 0x64, 0x0f,
	0xb1, 0x4c, 0x69, 0xc8, 0x4e, 0x68, 0xc8, 0x16, 0xb8, 0xbe, 0xdb, 0x5a, 0xba, 0xbb, 0xf3, 0xbf,
	0xf1, 0x57, 0x66, 0xd6, 0x6a, 0x90, 0x9d, 0x02, 0x98, 0x39, 0xa0, 0xee, 0x9f, 0x52, 0x4a, 0x85,
	0xe8, 0xfe, 0xa7, 0xe2, 0x3e, 0x4e, 0xf0, 0x23, 0x3f, 0x33, 0xfd, 0x2f, 0xc3, 0xb9, 0xd2, 0xe3,
	0x6e, 0x55, 0xe9, 0xcd, 0x95, 0x2b, 0x7e, 0x5e, 0x55, 0xae, 0x74, 0x6f, 0xea, 0x3e, 0xe9, 0x37,
	0xea, 0x98, 0xde, 0x2c, 0x2a, 0xac, 0x07, 0x07, 0x4d, 0x4a, 0x3e, 0x5f, 0xd3, 0x89, 0xa5, 0x1a,
	0xbb, 0x84, 0x67, 0x95, 0x8d, 0xa0, 0x2b, 0x74, 0x41, 0xd9, 0x0d, 0x6a, 0x6b, 0x59, 0x12, 0x72,
	0xf2, 0xc6, 0xcc, 0x54, 0x93, 0x5b, 0xdf, 0x96, 0x91, 0x8b, 0xcb, 0x8a, 0xef, 0x9a, 0xc2, 0x3e,
	0xc1, 0xa1, 0x2d, 0xf3, 0x0d, 0x26, 0x49, 0x9c, 0x8d, 0xcc, 0xac, 0xbc, 0xa5, 0x59, 0x59, 0x2e,
	0x76, 0x3e, 0xc3, 0xce, 0x97, 0xe1, 0x63, 0x26, 0xa6, 0x09, 0x46, 0x23, 0x4c, 0x31, 0x53, 0xac,
	0x03, 0x5b, 0xe1, 0x1c, 0x99, 0x2d, 0xd5, 0x0a, 0x6a, 0xac, 0xf7, 0x1b, 0xf6, 0xfb, 0x45, 0xae,
	0x44, 0x8a, 0xb2, 0xb2, 0xf2, 0xd8, 0x0d, 0x6c, 0x56, 0xc3, 0xb3, 0x6e, 0x73, 0x1f, 0x76, 0x6b,
	0xbb, 0xf0, 0xf8, 0x7c, 0x31, 0xa1, 0xe1, 0xa6, 0xf3, 0xdf, 0xfd, 0x3a, 0xed, 0xd6, 0xab, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x3a, 0xd6, 0x64, 0x75, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerOrderUpdateClient is the client API for CustomerOrderUpdate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerOrderUpdateClient interface {
	OrderUpdate(ctx context.Context, in *OrderItemInfo, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type customerOrderUpdateClient struct {
	cc *grpc.ClientConn
}

func NewCustomerOrderUpdateClient(cc *grpc.ClientConn) CustomerOrderUpdateClient {
	return &customerOrderUpdateClient{cc}
}

func (c *customerOrderUpdateClient) OrderUpdate(ctx context.Context, in *OrderItemInfo, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/OrderUpdateEvent.CustomerOrderUpdate/OrderUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerOrderUpdateServer is the server API for CustomerOrderUpdate service.
type CustomerOrderUpdateServer interface {
	OrderUpdate(context.Context, *OrderItemInfo) (*Acknowledgement, error)
}

func RegisterCustomerOrderUpdateServer(s *grpc.Server, srv CustomerOrderUpdateServer) {
	s.RegisterService(&_CustomerOrderUpdate_serviceDesc, srv)
}

func _CustomerOrderUpdate_OrderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderItemInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerOrderUpdateServer).OrderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderUpdateEvent.CustomerOrderUpdate/OrderUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerOrderUpdateServer).OrderUpdate(ctx, req.(*OrderItemInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerOrderUpdate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OrderUpdateEvent.CustomerOrderUpdate",
	HandlerType: (*CustomerOrderUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderUpdate",
			Handler:    _CustomerOrderUpdate_OrderUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orderUpdateEvent.proto",
}
